// Code generated by conjure-go. DO NOT EDIT.

package datasource

import (
	"github.com/nominal-io/nominal-api-go/scout/video/api"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

// Metadata specific to video files.
type VideoFileMetadata struct {
	/*
	   Specifies how to determine absolute timestamps for each frame in the video.
	   Can be an embedded MCAP manifest, an external sidecar file, or calculated
	   from a starting offset applied to presentation timestamps.
	*/
	TimestampManifest api.VideoFileTimestampManifest `conjure-docs:"Specifies how to determine absolute timestamps for each frame in the video.\nCan be an embedded MCAP manifest, an external sidecar file, or calculated\nfrom a starting offset applied to presentation timestamps." json:"timestampManifest"`
	/*
	   Cached aggregate metadata about the segments comprising this video file
	   after segmentation has completed. Includes frame counts, duration, and
	   frame rate. Empty until segmentation is complete.
	   Note: Min/max timestamps are stored in DatasetFile.bounds field.
	   Raw file size is stored in DatasetFile.fileSizeBytes.
	*/
	SegmentMetadata *VideoSegmentsMetadata `conjure-docs:"Cached aggregate metadata about the segments comprising this video file\nafter segmentation has completed. Includes frame counts, duration, and\nframe rate. Empty until segmentation is complete.\nNote: Min/max timestamps are stored in DatasetFile.bounds field.\nRaw file size is stored in DatasetFile.fileSizeBytes." json:"segmentMetadata,omitempty"`
}

func (o VideoFileMetadata) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *VideoFileMetadata) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

/*
Segment metadata for video files.
Lightweight version that excludes bounds and RID since those are stored elsewhere.
*/
type VideoSegmentsMetadata struct {
	// Total number of frames across all segments.
	NumFrames int `conjure-docs:"Total number of frames across all segments." json:"numFrames"`
	// Number of segments the video was split into.
	NumSegments int `conjure-docs:"Number of segments the video was split into." json:"numSegments"`
	// Scale factor applied to timestamps during segmentation.
	ScaleFactor float64 `conjure-docs:"Scale factor applied to timestamps during segmentation." json:"scaleFactor"`
	// Total duration of the video in seconds.
	MediaDurationSeconds float64 `conjure-docs:"Total duration of the video in seconds." json:"mediaDurationSeconds"`
	// Average frame rate (FPS) calculated as total frames / duration.
	MediaFrameRate float64 `conjure-docs:"Average frame rate (FPS) calculated as total frames / duration." json:"mediaFrameRate"`
}

func (o VideoSegmentsMetadata) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *VideoSegmentsMetadata) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}
