// Code generated by conjure-go. DO NOT EDIT.

//go:build go1.18

package authorization

import (
	"context"
	"fmt"
)

type ClaimWithT[T any] Claim

func (u *ClaimWithT[T]) Accept(ctx context.Context, v ClaimVisitorWithT[T]) (T, error) {
	var result T
	switch u.typ {
	default:
		if u.typ == "" {
			return result, fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknown(ctx, u.typ)
	case "string":
		if u.string == nil {
			return result, fmt.Errorf("field \"string\" is required")
		}
		return v.VisitString(ctx, *u.string)
	case "stringList":
		if u.stringList == nil {
			return result, fmt.Errorf("field \"stringList\" is required")
		}
		return v.VisitStringList(ctx, *u.stringList)
	}
}

func (u *ClaimWithT[T]) AcceptFuncs(stringFunc func(string) (T, error), stringListFunc func([]string) (T, error), unknownFunc func(string) (T, error)) (T, error) {
	var result T
	switch u.typ {
	default:
		if u.typ == "" {
			return result, fmt.Errorf("invalid value in union type")
		}
		return unknownFunc(u.typ)
	case "string":
		if u.string == nil {
			return result, fmt.Errorf("field \"string\" is required")
		}
		return stringFunc(*u.string)
	case "stringList":
		if u.stringList == nil {
			return result, fmt.Errorf("field \"stringList\" is required")
		}
		return stringListFunc(*u.stringList)
	}
}

func (u *ClaimWithT[T]) StringNoopSuccess(string) (T, error) {
	var result T
	return result, nil
}

func (u *ClaimWithT[T]) StringListNoopSuccess([]string) (T, error) {
	var result T
	return result, nil
}

func (u *ClaimWithT[T]) ErrorOnUnknown(typeName string) (T, error) {
	var result T
	return result, fmt.Errorf("invalid value in union type. Type name: %s", typeName)
}

type ClaimVisitorWithT[T any] interface {
	VisitString(ctx context.Context, v string) (T, error)
	VisitStringList(ctx context.Context, v []string) (T, error)
	VisitUnknown(ctx context.Context, typ string) (T, error)
}
