// Code generated by conjure-go. DO NOT EDIT.

package savedviews

import (
	"context"
	"fmt"
	"net/url"

	"github.com/nominal-io/nominal-api-go/internal/conjureerrors"
	api1 "github.com/nominal-io/nominal-api-go/scout/rids/api"
	"github.com/nominal-io/nominal-api-go/scout/savedviews/api"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
)

/*
Saved Views allow users to store and reuse filter and table display configurations across
assets, runs, checklists, and more. They can be favorited, archived, and shared across a workspace.
*/
type SavedViewServiceClient interface {
	/*
	   Creates a new saved view in the given workspace. If no workspace is specified,
	   it is created in the user's default workspace.
	*/
	CreateSavedView(ctx context.Context, authHeader bearertoken.Token, requestArg api.CreateSavedViewRequest) (api.CreateSavedViewResponse, error)
	// Fetches a saved view by RID. Throws NOT_FOUND if it does not exist.
	GetSavedView(ctx context.Context, authHeader bearertoken.Token, savedViewRidArg api1.SavedViewRid) (api.GetSavedViewResponse, error)
	// Retrieves multiple saved views. Any invalid or unknown RIDs are omitted from the response.
	BatchGetSavedViews(ctx context.Context, authHeader bearertoken.Token, savedViewRidsArg []api1.SavedViewRid) (api.BatchGetSavedViewsResponse, error)
	// Searches for saved views using a nested query expression. Supports pagination.
	SearchSavedViews(ctx context.Context, authHeader bearertoken.Token, requestArg api.SearchSavedViewsRequest) (api.SearchSavedViewsResponse, error)
	/*
	   Updates metadata, search filters, or display settings for an existing saved view.
	   Throws NOT_FOUND if the view doesn't exist and INVALID_ARGUMENT if it is archived.
	*/
	UpdateSavedView(ctx context.Context, authHeader bearertoken.Token, savedViewRidArg api1.SavedViewRid, requestArg api.UpdateSavedViewRequest) (api.UpdateSavedViewResponse, error)
	// Archives the specified saved view. Archived views are hidden from search.
	ArchiveSavedView(ctx context.Context, authHeader bearertoken.Token, savedViewRidArg api1.SavedViewRid) error
	// Restores archived saved view, making them discoverable in search again.
	UnarchiveSavedView(ctx context.Context, authHeader bearertoken.Token, savedViewRidArg api1.SavedViewRid) error
}

type savedViewServiceClient struct {
	client httpclient.Client
}

func NewSavedViewServiceClient(client httpclient.Client) SavedViewServiceClient {
	return &savedViewServiceClient{client: client}
}

func (c *savedViewServiceClient) CreateSavedView(ctx context.Context, authHeader bearertoken.Token, requestArg api.CreateSavedViewRequest) (api.CreateSavedViewResponse, error) {
	var defaultReturnVal api.CreateSavedViewResponse
	var returnVal *api.CreateSavedViewResponse
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("CreateSavedView"))
	requestParams = append(requestParams, httpclient.WithRequestMethod("POST"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/scout/saved-views/v1"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Do(ctx, requestParams...); err != nil {
		return defaultReturnVal, werror.WrapWithContextParams(ctx, err, "createSavedView failed")
	}
	if returnVal == nil {
		return defaultReturnVal, werror.ErrorWithContextParams(ctx, "createSavedView response cannot be nil")
	}
	return *returnVal, nil
}

func (c *savedViewServiceClient) GetSavedView(ctx context.Context, authHeader bearertoken.Token, savedViewRidArg api1.SavedViewRid) (api.GetSavedViewResponse, error) {
	var defaultReturnVal api.GetSavedViewResponse
	var returnVal *api.GetSavedViewResponse
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("GetSavedView"))
	requestParams = append(requestParams, httpclient.WithRequestMethod("GET"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/scout/saved-views/v1/%s", url.PathEscape(fmt.Sprint(savedViewRidArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Do(ctx, requestParams...); err != nil {
		return defaultReturnVal, werror.WrapWithContextParams(ctx, err, "getSavedView failed")
	}
	if returnVal == nil {
		return defaultReturnVal, werror.ErrorWithContextParams(ctx, "getSavedView response cannot be nil")
	}
	return *returnVal, nil
}

func (c *savedViewServiceClient) BatchGetSavedViews(ctx context.Context, authHeader bearertoken.Token, savedViewRidsArg []api1.SavedViewRid) (api.BatchGetSavedViewsResponse, error) {
	var defaultReturnVal api.BatchGetSavedViewsResponse
	var returnVal *api.BatchGetSavedViewsResponse
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("BatchGetSavedViews"))
	requestParams = append(requestParams, httpclient.WithRequestMethod("POST"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/scout/saved-views/v1/batch-get"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(savedViewRidsArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Do(ctx, requestParams...); err != nil {
		return defaultReturnVal, werror.WrapWithContextParams(ctx, err, "batchGetSavedViews failed")
	}
	if returnVal == nil {
		return defaultReturnVal, werror.ErrorWithContextParams(ctx, "batchGetSavedViews response cannot be nil")
	}
	return *returnVal, nil
}

func (c *savedViewServiceClient) SearchSavedViews(ctx context.Context, authHeader bearertoken.Token, requestArg api.SearchSavedViewsRequest) (api.SearchSavedViewsResponse, error) {
	var defaultReturnVal api.SearchSavedViewsResponse
	var returnVal *api.SearchSavedViewsResponse
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("SearchSavedViews"))
	requestParams = append(requestParams, httpclient.WithRequestMethod("POST"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/scout/saved-views/v1/search"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Do(ctx, requestParams...); err != nil {
		return defaultReturnVal, werror.WrapWithContextParams(ctx, err, "searchSavedViews failed")
	}
	if returnVal == nil {
		return defaultReturnVal, werror.ErrorWithContextParams(ctx, "searchSavedViews response cannot be nil")
	}
	return *returnVal, nil
}

func (c *savedViewServiceClient) UpdateSavedView(ctx context.Context, authHeader bearertoken.Token, savedViewRidArg api1.SavedViewRid, requestArg api.UpdateSavedViewRequest) (api.UpdateSavedViewResponse, error) {
	var defaultReturnVal api.UpdateSavedViewResponse
	var returnVal *api.UpdateSavedViewResponse
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("UpdateSavedView"))
	requestParams = append(requestParams, httpclient.WithRequestMethod("PUT"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/scout/saved-views/v1/%s", url.PathEscape(fmt.Sprint(savedViewRidArg))))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Do(ctx, requestParams...); err != nil {
		return defaultReturnVal, werror.WrapWithContextParams(ctx, err, "updateSavedView failed")
	}
	if returnVal == nil {
		return defaultReturnVal, werror.ErrorWithContextParams(ctx, "updateSavedView response cannot be nil")
	}
	return *returnVal, nil
}

func (c *savedViewServiceClient) ArchiveSavedView(ctx context.Context, authHeader bearertoken.Token, savedViewRidArg api1.SavedViewRid) error {
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ArchiveSavedView"))
	requestParams = append(requestParams, httpclient.WithRequestMethod("POST"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/scout/saved-views/v1/%s/archive", url.PathEscape(fmt.Sprint(savedViewRidArg))))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Do(ctx, requestParams...); err != nil {
		return werror.WrapWithContextParams(ctx, err, "archiveSavedView failed")
	}
	return nil
}

func (c *savedViewServiceClient) UnarchiveSavedView(ctx context.Context, authHeader bearertoken.Token, savedViewRidArg api1.SavedViewRid) error {
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("UnarchiveSavedView"))
	requestParams = append(requestParams, httpclient.WithRequestMethod("POST"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/scout/saved-views/v1/%s/unarchive", url.PathEscape(fmt.Sprint(savedViewRidArg))))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Do(ctx, requestParams...); err != nil {
		return werror.WrapWithContextParams(ctx, err, "unarchiveSavedView failed")
	}
	return nil
}

/*
Saved Views allow users to store and reuse filter and table display configurations across
assets, runs, checklists, and more. They can be favorited, archived, and shared across a workspace.
*/
type SavedViewServiceClientWithAuth interface {
	/*
	   Creates a new saved view in the given workspace. If no workspace is specified,
	   it is created in the user's default workspace.
	*/
	CreateSavedView(ctx context.Context, requestArg api.CreateSavedViewRequest) (api.CreateSavedViewResponse, error)
	// Fetches a saved view by RID. Throws NOT_FOUND if it does not exist.
	GetSavedView(ctx context.Context, savedViewRidArg api1.SavedViewRid) (api.GetSavedViewResponse, error)
	// Retrieves multiple saved views. Any invalid or unknown RIDs are omitted from the response.
	BatchGetSavedViews(ctx context.Context, savedViewRidsArg []api1.SavedViewRid) (api.BatchGetSavedViewsResponse, error)
	// Searches for saved views using a nested query expression. Supports pagination.
	SearchSavedViews(ctx context.Context, requestArg api.SearchSavedViewsRequest) (api.SearchSavedViewsResponse, error)
	/*
	   Updates metadata, search filters, or display settings for an existing saved view.
	   Throws NOT_FOUND if the view doesn't exist and INVALID_ARGUMENT if it is archived.
	*/
	UpdateSavedView(ctx context.Context, savedViewRidArg api1.SavedViewRid, requestArg api.UpdateSavedViewRequest) (api.UpdateSavedViewResponse, error)
	// Archives the specified saved view. Archived views are hidden from search.
	ArchiveSavedView(ctx context.Context, savedViewRidArg api1.SavedViewRid) error
	// Restores archived saved view, making them discoverable in search again.
	UnarchiveSavedView(ctx context.Context, savedViewRidArg api1.SavedViewRid) error
}

func NewSavedViewServiceClientWithAuth(client SavedViewServiceClient, authHeader bearertoken.Token) SavedViewServiceClientWithAuth {
	return &savedViewServiceClientWithAuth{client: client, authHeader: authHeader}
}

type savedViewServiceClientWithAuth struct {
	client     SavedViewServiceClient
	authHeader bearertoken.Token
}

func (c *savedViewServiceClientWithAuth) CreateSavedView(ctx context.Context, requestArg api.CreateSavedViewRequest) (api.CreateSavedViewResponse, error) {
	return c.client.CreateSavedView(ctx, c.authHeader, requestArg)
}

func (c *savedViewServiceClientWithAuth) GetSavedView(ctx context.Context, savedViewRidArg api1.SavedViewRid) (api.GetSavedViewResponse, error) {
	return c.client.GetSavedView(ctx, c.authHeader, savedViewRidArg)
}

func (c *savedViewServiceClientWithAuth) BatchGetSavedViews(ctx context.Context, savedViewRidsArg []api1.SavedViewRid) (api.BatchGetSavedViewsResponse, error) {
	return c.client.BatchGetSavedViews(ctx, c.authHeader, savedViewRidsArg)
}

func (c *savedViewServiceClientWithAuth) SearchSavedViews(ctx context.Context, requestArg api.SearchSavedViewsRequest) (api.SearchSavedViewsResponse, error) {
	return c.client.SearchSavedViews(ctx, c.authHeader, requestArg)
}

func (c *savedViewServiceClientWithAuth) UpdateSavedView(ctx context.Context, savedViewRidArg api1.SavedViewRid, requestArg api.UpdateSavedViewRequest) (api.UpdateSavedViewResponse, error) {
	return c.client.UpdateSavedView(ctx, c.authHeader, savedViewRidArg, requestArg)
}

func (c *savedViewServiceClientWithAuth) ArchiveSavedView(ctx context.Context, savedViewRidArg api1.SavedViewRid) error {
	return c.client.ArchiveSavedView(ctx, c.authHeader, savedViewRidArg)
}

func (c *savedViewServiceClientWithAuth) UnarchiveSavedView(ctx context.Context, savedViewRidArg api1.SavedViewRid) error {
	return c.client.UnarchiveSavedView(ctx, c.authHeader, savedViewRidArg)
}

func NewSavedViewServiceClientWithTokenProvider(client SavedViewServiceClient, tokenProvider httpclient.TokenProvider) SavedViewServiceClientWithAuth {
	return &savedViewServiceClientWithTokenProvider{client: client, tokenProvider: tokenProvider}
}

type savedViewServiceClientWithTokenProvider struct {
	client        SavedViewServiceClient
	tokenProvider httpclient.TokenProvider
}

func (c *savedViewServiceClientWithTokenProvider) CreateSavedView(ctx context.Context, requestArg api.CreateSavedViewRequest) (api.CreateSavedViewResponse, error) {
	var defaultReturnVal api.CreateSavedViewResponse
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return defaultReturnVal, err
	}
	return c.client.CreateSavedView(ctx, bearertoken.Token(token), requestArg)
}

func (c *savedViewServiceClientWithTokenProvider) GetSavedView(ctx context.Context, savedViewRidArg api1.SavedViewRid) (api.GetSavedViewResponse, error) {
	var defaultReturnVal api.GetSavedViewResponse
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return defaultReturnVal, err
	}
	return c.client.GetSavedView(ctx, bearertoken.Token(token), savedViewRidArg)
}

func (c *savedViewServiceClientWithTokenProvider) BatchGetSavedViews(ctx context.Context, savedViewRidsArg []api1.SavedViewRid) (api.BatchGetSavedViewsResponse, error) {
	var defaultReturnVal api.BatchGetSavedViewsResponse
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return defaultReturnVal, err
	}
	return c.client.BatchGetSavedViews(ctx, bearertoken.Token(token), savedViewRidsArg)
}

func (c *savedViewServiceClientWithTokenProvider) SearchSavedViews(ctx context.Context, requestArg api.SearchSavedViewsRequest) (api.SearchSavedViewsResponse, error) {
	var defaultReturnVal api.SearchSavedViewsResponse
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return defaultReturnVal, err
	}
	return c.client.SearchSavedViews(ctx, bearertoken.Token(token), requestArg)
}

func (c *savedViewServiceClientWithTokenProvider) UpdateSavedView(ctx context.Context, savedViewRidArg api1.SavedViewRid, requestArg api.UpdateSavedViewRequest) (api.UpdateSavedViewResponse, error) {
	var defaultReturnVal api.UpdateSavedViewResponse
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return defaultReturnVal, err
	}
	return c.client.UpdateSavedView(ctx, bearertoken.Token(token), savedViewRidArg, requestArg)
}

func (c *savedViewServiceClientWithTokenProvider) ArchiveSavedView(ctx context.Context, savedViewRidArg api1.SavedViewRid) error {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return err
	}
	return c.client.ArchiveSavedView(ctx, bearertoken.Token(token), savedViewRidArg)
}

func (c *savedViewServiceClientWithTokenProvider) UnarchiveSavedView(ctx context.Context, savedViewRidArg api1.SavedViewRid) error {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return err
	}
	return c.client.UnarchiveSavedView(ctx, bearertoken.Token(token), savedViewRidArg)
}
