// Code generated by conjure-go. DO NOT EDIT.

package api

import (
	"strings"
)

type ScanPattern struct {
	val ScanPattern_Value
}

type ScanPattern_Value string

const (
	ScanPattern_ROTATING    ScanPattern_Value = "ROTATING"
	ScanPattern_SOLID_STATE ScanPattern_Value = "SOLID_STATE"
	ScanPattern_FLASH       ScanPattern_Value = "FLASH"
	ScanPattern_MECHANICAL  ScanPattern_Value = "MECHANICAL"
	ScanPattern_UNKNOWN     ScanPattern_Value = "UNKNOWN"
)

// ScanPattern_Values returns all known variants of ScanPattern.
func ScanPattern_Values() []ScanPattern_Value {
	return []ScanPattern_Value{ScanPattern_ROTATING, ScanPattern_SOLID_STATE, ScanPattern_FLASH, ScanPattern_MECHANICAL}
}

func New_ScanPattern(value ScanPattern_Value) ScanPattern {
	return ScanPattern{val: value}
}

// IsUnknown returns false for all known variants of ScanPattern and true otherwise.
func (e ScanPattern) IsUnknown() bool {
	switch e.val {
	case ScanPattern_ROTATING, ScanPattern_SOLID_STATE, ScanPattern_FLASH, ScanPattern_MECHANICAL:
		return false
	}
	return true
}

func (e ScanPattern) Value() ScanPattern_Value {
	if e.IsUnknown() {
		return ScanPattern_UNKNOWN
	}
	return e.val
}

func (e ScanPattern) String() string {
	return string(e.val)
}

func (e ScanPattern) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *ScanPattern) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_ScanPattern(ScanPattern_Value(v))
	case "ROTATING":
		*e = New_ScanPattern(ScanPattern_ROTATING)
	case "SOLID_STATE":
		*e = New_ScanPattern(ScanPattern_SOLID_STATE)
	case "FLASH":
		*e = New_ScanPattern(ScanPattern_FLASH)
	case "MECHANICAL":
		*e = New_ScanPattern(ScanPattern_MECHANICAL)
	}
	return nil
}

type SortField struct {
	val SortField_Value
}

type SortField_Value string

const (
	SortField_CREATED_AT SortField_Value = "CREATED_AT"
	SortField_UNKNOWN    SortField_Value = "UNKNOWN"
)

// SortField_Values returns all known variants of SortField.
func SortField_Values() []SortField_Value {
	return []SortField_Value{SortField_CREATED_AT}
}

func New_SortField(value SortField_Value) SortField {
	return SortField{val: value}
}

// IsUnknown returns false for all known variants of SortField and true otherwise.
func (e SortField) IsUnknown() bool {
	switch e.val {
	case SortField_CREATED_AT:
		return false
	}
	return true
}

func (e SortField) Value() SortField_Value {
	if e.IsUnknown() {
		return SortField_UNKNOWN
	}
	return e.val
}

func (e SortField) String() string {
	return string(e.val)
}

func (e SortField) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *SortField) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_SortField(SortField_Value(v))
	case "CREATED_AT":
		*e = New_SortField(SortField_CREATED_AT)
	}
	return nil
}

// The type of spatial data stored in a spatial asset.
type SpatialType struct {
	val SpatialType_Value
}

type SpatialType_Value string

const (
	SpatialType_POINT_CLOUD SpatialType_Value = "POINT_CLOUD"
	SpatialType_UNKNOWN     SpatialType_Value = "UNKNOWN"
)

// SpatialType_Values returns all known variants of SpatialType.
func SpatialType_Values() []SpatialType_Value {
	return []SpatialType_Value{SpatialType_POINT_CLOUD}
}

func New_SpatialType(value SpatialType_Value) SpatialType {
	return SpatialType{val: value}
}

// IsUnknown returns false for all known variants of SpatialType and true otherwise.
func (e SpatialType) IsUnknown() bool {
	switch e.val {
	case SpatialType_POINT_CLOUD:
		return false
	}
	return true
}

func (e SpatialType) Value() SpatialType_Value {
	if e.IsUnknown() {
		return SpatialType_UNKNOWN
	}
	return e.val
}

func (e SpatialType) String() string {
	return string(e.val)
}

func (e SpatialType) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *SpatialType) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_SpatialType(SpatialType_Value(v))
	case "POINT_CLOUD":
		*e = New_SpatialType(SpatialType_POINT_CLOUD)
	}
	return nil
}
