// Code generated by conjure-go. DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/nominal-io/nominal-api-go/api/rids"
	"github.com/nominal-io/nominal-api-go/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
	"github.com/palantir/pkg/uuid"
	werror "github.com/palantir/witchcraft-go-error"
)

// safelogging:@Safe
type notAuthorized struct {
	SpatialRid rids.SpatialRid `json:"spatialRid" safelogging:"@Safe"`
}

func (o notAuthorized) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *notAuthorized) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewNotAuthorized returns new instance of NotAuthorized error.
func NewNotAuthorized(spatialRidArg rids.SpatialRid) *NotAuthorized {
	return &NotAuthorized{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), notAuthorized: notAuthorized{SpatialRid: spatialRidArg}}
}

// WrapWithNotAuthorized returns new instance of NotAuthorized error wrapping an existing error.
func WrapWithNotAuthorized(err error, spatialRidArg rids.SpatialRid) *NotAuthorized {
	return &NotAuthorized{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, notAuthorized: notAuthorized{SpatialRid: spatialRidArg}}
}

// NotAuthorized is an error type.
type NotAuthorized struct {
	errorInstanceID uuid.UUID
	notAuthorized
	cause error
	stack werror.StackTrace
}

// IsNotAuthorized returns true if err is an instance of NotAuthorized.
func IsNotAuthorized(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*NotAuthorized)
	return ok
}

func (e *NotAuthorized) Error() string {
	return fmt.Sprintf("PERMISSION_DENIED Spatial:NotAuthorized (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *NotAuthorized) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *NotAuthorized) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *NotAuthorized) Message() string {
	return "PERMISSION_DENIED Spatial:NotAuthorized"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *NotAuthorized) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *NotAuthorized) Code() errors.ErrorCode {
	return errors.PermissionDenied
}

// Name returns an error name identifying error type.
func (e *NotAuthorized) Name() string {
	return "Spatial:NotAuthorized"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *NotAuthorized) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *NotAuthorized) Parameters() map[string]interface{} {
	return map[string]interface{}{"spatialRid": e.SpatialRid}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *NotAuthorized) safeParams() map[string]interface{} {
	return map[string]interface{}{"spatialRid": e.SpatialRid, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *NotAuthorized) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *NotAuthorized) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *NotAuthorized) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e NotAuthorized) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.notAuthorized)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.PermissionDenied, ErrorName: "Spatial:NotAuthorized", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *NotAuthorized) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters notAuthorized
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.notAuthorized = parameters
	return nil
}

// safelogging:@Safe
type spatialNotFound struct {
	SpatialRid rids.SpatialRid `json:"spatialRid" safelogging:"@Safe"`
}

func (o spatialNotFound) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *spatialNotFound) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewSpatialNotFound returns new instance of SpatialNotFound error.
func NewSpatialNotFound(spatialRidArg rids.SpatialRid) *SpatialNotFound {
	return &SpatialNotFound{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), spatialNotFound: spatialNotFound{SpatialRid: spatialRidArg}}
}

// WrapWithSpatialNotFound returns new instance of SpatialNotFound error wrapping an existing error.
func WrapWithSpatialNotFound(err error, spatialRidArg rids.SpatialRid) *SpatialNotFound {
	return &SpatialNotFound{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, spatialNotFound: spatialNotFound{SpatialRid: spatialRidArg}}
}

// SpatialNotFound is an error type.
type SpatialNotFound struct {
	errorInstanceID uuid.UUID
	spatialNotFound
	cause error
	stack werror.StackTrace
}

// IsSpatialNotFound returns true if err is an instance of SpatialNotFound.
func IsSpatialNotFound(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*SpatialNotFound)
	return ok
}

func (e *SpatialNotFound) Error() string {
	return fmt.Sprintf("NOT_FOUND Spatial:SpatialNotFound (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *SpatialNotFound) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *SpatialNotFound) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *SpatialNotFound) Message() string {
	return "NOT_FOUND Spatial:SpatialNotFound"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *SpatialNotFound) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *SpatialNotFound) Code() errors.ErrorCode {
	return errors.NotFound
}

// Name returns an error name identifying error type.
func (e *SpatialNotFound) Name() string {
	return "Spatial:SpatialNotFound"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *SpatialNotFound) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *SpatialNotFound) Parameters() map[string]interface{} {
	return map[string]interface{}{"spatialRid": e.SpatialRid}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *SpatialNotFound) safeParams() map[string]interface{} {
	return map[string]interface{}{"spatialRid": e.SpatialRid, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *SpatialNotFound) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *SpatialNotFound) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *SpatialNotFound) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e SpatialNotFound) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.spatialNotFound)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.NotFound, ErrorName: "Spatial:SpatialNotFound", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *SpatialNotFound) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters spatialNotFound
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.spatialNotFound = parameters
	return nil
}

func init() {
	conjureerrors.RegisterErrorType("Spatial:NotAuthorized", reflect.TypeOf(NotAuthorized{}))
	conjureerrors.RegisterErrorType("Spatial:SpatialNotFound", reflect.TypeOf(SpatialNotFound{}))
}
