// Code generated by conjure-go. DO NOT EDIT.

package workspace

import (
	"github.com/nominal-io/nominal-api-go/api/ids"
	"github.com/nominal-io/nominal-api-go/api/rids"
	"github.com/nominal-io/nominal-api-go/authentication/api"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

type ProcedureSettingsV1 struct {
	/*
	   A list of procedures that are elevated to the workspace-level.
	   They will be available for execution in a top-level context, rather
	   than just from the procedure details page.
	*/
	WorkspaceProcedures []rids.ProcedureRid `conjure-docs:"A list of procedures that are elevated to the workspace-level.\nThey will be available for execution in a top-level context, rather\nthan just from the procedure details page." json:"workspaceProcedures"`
}

func (o ProcedureSettingsV1) MarshalJSON() ([]byte, error) {
	if o.WorkspaceProcedures == nil {
		o.WorkspaceProcedures = make([]rids.ProcedureRid, 0)
	}
	type _tmpProcedureSettingsV1 ProcedureSettingsV1
	return safejson.Marshal(_tmpProcedureSettingsV1(o))
}

func (o *ProcedureSettingsV1) UnmarshalJSON(data []byte) error {
	type _tmpProcedureSettingsV1 ProcedureSettingsV1
	var rawProcedureSettingsV1 _tmpProcedureSettingsV1
	if err := safejson.Unmarshal(data, &rawProcedureSettingsV1); err != nil {
		return err
	}
	if rawProcedureSettingsV1.WorkspaceProcedures == nil {
		rawProcedureSettingsV1.WorkspaceProcedures = make([]rids.ProcedureRid, 0)
	}
	*o = ProcedureSettingsV1(rawProcedureSettingsV1)
	return nil
}

func (o ProcedureSettingsV1) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *ProcedureSettingsV1) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// The request to remove a field from a workspace.
type RemoveType struct{}

func (o RemoveType) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *RemoveType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type UpdateWorkspaceRequest struct {
	DisplayName *UpdateOrRemoveWorkspaceDisplayName `json:"displayName,omitempty"`
	Symbol      *UpdateOrRemoveWorkspaceSymbol      `json:"symbol,omitempty"`
	Settings    *WorkspaceSettings                  `json:"settings,omitempty"`
}

func (o UpdateWorkspaceRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpdateWorkspaceRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type Workspace struct {
	// A unique identifier for the workspace within the organization. The workspace ID must be lower case alphanumeric characters, optionally separated by hyphens.
	Id          ids.WorkspaceId   `conjure-docs:"A unique identifier for the workspace within the organization. The workspace ID must be lower case alphanumeric characters, optionally separated by hyphens." json:"id"`
	Rid         rids.WorkspaceRid `json:"rid"`
	Org         api.OrgRid        `json:"org"`
	DisplayName *string           `json:"displayName,omitempty"`
	Symbol      *WorkspaceSymbol  `json:"symbol,omitempty"`
	Settings    WorkspaceSettings `json:"settings"`
}

func (o Workspace) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Workspace) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type WorkspaceSettings struct {
	RefNames   *PreferredRefNameConfiguration `json:"refNames,omitempty"`
	Procedures *ProcedureSettings             `json:"procedures,omitempty"`
}

func (o WorkspaceSettings) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *WorkspaceSettings) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}
