// Code generated by conjure-go. DO NOT EDIT.

package api

import (
	"context"
	"fmt"
	"net/url"

	"github.com/nominal-io/nominal-api-go/api/rids"
	"github.com/nominal-io/nominal-api-go/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
)

/*
Service for managing demo workbooks in sandbox workspaces.
All endpoints validate that the provided workspace has the human-readable ID "sandbox".
*/
type SandboxWorkspaceServiceClient interface {
	// Returns the list of demo workbook RIDs for the given sandbox workspace.
	GetDemoWorkbooks(ctx context.Context, authHeader bearertoken.Token, workspaceRidArg rids.WorkspaceRid) (GetDemoWorkbooksResponse, error)
	// Sets the list of demo workbook RIDs for the given sandbox workspace, replacing any existing entries.
	SetDemoWorkbooks(ctx context.Context, authHeader bearertoken.Token, workspaceRidArg rids.WorkspaceRid, requestArg SetDemoWorkbooksRequest) error
}

type sandboxWorkspaceServiceClient struct {
	client httpclient.Client
}

func NewSandboxWorkspaceServiceClient(client httpclient.Client) SandboxWorkspaceServiceClient {
	return &sandboxWorkspaceServiceClient{client: client}
}

func (c *sandboxWorkspaceServiceClient) GetDemoWorkbooks(ctx context.Context, authHeader bearertoken.Token, workspaceRidArg rids.WorkspaceRid) (GetDemoWorkbooksResponse, error) {
	var returnVal *GetDemoWorkbooksResponse
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("GetDemoWorkbooks"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/scout/v1/sandbox-workspace/%s/demo-workbooks", url.PathEscape(fmt.Sprint(workspaceRidArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(GetDemoWorkbooksResponse), werror.WrapWithContextParams(ctx, err, "getDemoWorkbooks failed")
	}
	if returnVal == nil {
		return *new(GetDemoWorkbooksResponse), werror.ErrorWithContextParams(ctx, "getDemoWorkbooks response cannot be nil")
	}
	return *returnVal, nil
}

func (c *sandboxWorkspaceServiceClient) SetDemoWorkbooks(ctx context.Context, authHeader bearertoken.Token, workspaceRidArg rids.WorkspaceRid, requestArg SetDemoWorkbooksRequest) error {
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("SetDemoWorkbooks"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/scout/v1/sandbox-workspace/%s/demo-workbooks", url.PathEscape(fmt.Sprint(workspaceRidArg))))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Put(ctx, requestParams...); err != nil {
		return werror.WrapWithContextParams(ctx, err, "setDemoWorkbooks failed")
	}
	return nil
}

/*
Service for managing demo workbooks in sandbox workspaces.
All endpoints validate that the provided workspace has the human-readable ID "sandbox".
*/
type SandboxWorkspaceServiceClientWithAuth interface {
	// Returns the list of demo workbook RIDs for the given sandbox workspace.
	GetDemoWorkbooks(ctx context.Context, workspaceRidArg rids.WorkspaceRid) (GetDemoWorkbooksResponse, error)
	// Sets the list of demo workbook RIDs for the given sandbox workspace, replacing any existing entries.
	SetDemoWorkbooks(ctx context.Context, workspaceRidArg rids.WorkspaceRid, requestArg SetDemoWorkbooksRequest) error
}

func NewSandboxWorkspaceServiceClientWithAuth(client SandboxWorkspaceServiceClient, authHeader bearertoken.Token) SandboxWorkspaceServiceClientWithAuth {
	return &sandboxWorkspaceServiceClientWithAuth{client: client, authHeader: authHeader}
}

type sandboxWorkspaceServiceClientWithAuth struct {
	client     SandboxWorkspaceServiceClient
	authHeader bearertoken.Token
}

func (c *sandboxWorkspaceServiceClientWithAuth) GetDemoWorkbooks(ctx context.Context, workspaceRidArg rids.WorkspaceRid) (GetDemoWorkbooksResponse, error) {
	return c.client.GetDemoWorkbooks(ctx, c.authHeader, workspaceRidArg)
}

func (c *sandboxWorkspaceServiceClientWithAuth) SetDemoWorkbooks(ctx context.Context, workspaceRidArg rids.WorkspaceRid, requestArg SetDemoWorkbooksRequest) error {
	return c.client.SetDemoWorkbooks(ctx, c.authHeader, workspaceRidArg, requestArg)
}

func NewSandboxWorkspaceServiceClientWithTokenProvider(client SandboxWorkspaceServiceClient, tokenProvider httpclient.TokenProvider) SandboxWorkspaceServiceClientWithAuth {
	return &sandboxWorkspaceServiceClientWithTokenProvider{client: client, tokenProvider: tokenProvider}
}

type sandboxWorkspaceServiceClientWithTokenProvider struct {
	client        SandboxWorkspaceServiceClient
	tokenProvider httpclient.TokenProvider
}

func (c *sandboxWorkspaceServiceClientWithTokenProvider) GetDemoWorkbooks(ctx context.Context, workspaceRidArg rids.WorkspaceRid) (GetDemoWorkbooksResponse, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(GetDemoWorkbooksResponse), err
	}
	return c.client.GetDemoWorkbooks(ctx, bearertoken.Token(token), workspaceRidArg)
}

func (c *sandboxWorkspaceServiceClientWithTokenProvider) SetDemoWorkbooks(ctx context.Context, workspaceRidArg rids.WorkspaceRid, requestArg SetDemoWorkbooksRequest) error {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return err
	}
	return c.client.SetDemoWorkbooks(ctx, bearertoken.Token(token), workspaceRidArg, requestArg)
}
