// Code generated by conjure-go. DO NOT EDIT.

package api

import (
	"github.com/nominal-io/nominal-api-go/scout/rids/api"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

// safelogging:@Safe
type GetDemoWorkbooksResponse struct {
	NotebookRids []api.NotebookRid `json:"notebookRids" safelogging:"@Safe"`
}

func (o GetDemoWorkbooksResponse) MarshalJSON() ([]byte, error) {
	if o.NotebookRids == nil {
		o.NotebookRids = make([]api.NotebookRid, 0)
	}
	type _tmpGetDemoWorkbooksResponse GetDemoWorkbooksResponse
	return safejson.Marshal(_tmpGetDemoWorkbooksResponse(o))
}

func (o *GetDemoWorkbooksResponse) UnmarshalJSON(data []byte) error {
	type _tmpGetDemoWorkbooksResponse GetDemoWorkbooksResponse
	var rawGetDemoWorkbooksResponse _tmpGetDemoWorkbooksResponse
	if err := safejson.Unmarshal(data, &rawGetDemoWorkbooksResponse); err != nil {
		return err
	}
	if rawGetDemoWorkbooksResponse.NotebookRids == nil {
		rawGetDemoWorkbooksResponse.NotebookRids = make([]api.NotebookRid, 0)
	}
	*o = GetDemoWorkbooksResponse(rawGetDemoWorkbooksResponse)
	return nil
}

func (o GetDemoWorkbooksResponse) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *GetDemoWorkbooksResponse) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// Version 1 of sandbox workspace settings.
// safelogging:@Safe
type SandboxWorkspaceSettingsV1 struct {
	DemoWorkbooks []api.NotebookRid `json:"demoWorkbooks" safelogging:"@Safe"`
}

func (o SandboxWorkspaceSettingsV1) MarshalJSON() ([]byte, error) {
	if o.DemoWorkbooks == nil {
		o.DemoWorkbooks = make([]api.NotebookRid, 0)
	}
	type _tmpSandboxWorkspaceSettingsV1 SandboxWorkspaceSettingsV1
	return safejson.Marshal(_tmpSandboxWorkspaceSettingsV1(o))
}

func (o *SandboxWorkspaceSettingsV1) UnmarshalJSON(data []byte) error {
	type _tmpSandboxWorkspaceSettingsV1 SandboxWorkspaceSettingsV1
	var rawSandboxWorkspaceSettingsV1 _tmpSandboxWorkspaceSettingsV1
	if err := safejson.Unmarshal(data, &rawSandboxWorkspaceSettingsV1); err != nil {
		return err
	}
	if rawSandboxWorkspaceSettingsV1.DemoWorkbooks == nil {
		rawSandboxWorkspaceSettingsV1.DemoWorkbooks = make([]api.NotebookRid, 0)
	}
	*o = SandboxWorkspaceSettingsV1(rawSandboxWorkspaceSettingsV1)
	return nil
}

func (o SandboxWorkspaceSettingsV1) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *SandboxWorkspaceSettingsV1) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// safelogging:@Safe
type SetDemoWorkbooksRequest struct {
	NotebookRids []api.NotebookRid `json:"notebookRids" safelogging:"@Safe"`
}

func (o SetDemoWorkbooksRequest) MarshalJSON() ([]byte, error) {
	if o.NotebookRids == nil {
		o.NotebookRids = make([]api.NotebookRid, 0)
	}
	type _tmpSetDemoWorkbooksRequest SetDemoWorkbooksRequest
	return safejson.Marshal(_tmpSetDemoWorkbooksRequest(o))
}

func (o *SetDemoWorkbooksRequest) UnmarshalJSON(data []byte) error {
	type _tmpSetDemoWorkbooksRequest SetDemoWorkbooksRequest
	var rawSetDemoWorkbooksRequest _tmpSetDemoWorkbooksRequest
	if err := safejson.Unmarshal(data, &rawSetDemoWorkbooksRequest); err != nil {
		return err
	}
	if rawSetDemoWorkbooksRequest.NotebookRids == nil {
		rawSetDemoWorkbooksRequest.NotebookRids = make([]api.NotebookRid, 0)
	}
	*o = SetDemoWorkbooksRequest(rawSetDemoWorkbooksRequest)
	return nil
}

func (o SetDemoWorkbooksRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *SetDemoWorkbooksRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}
