// Code generated by conjure-go. DO NOT EDIT.

package api

import (
	"github.com/nominal-io/nominal-api/scout/rids/api"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

type ComparisonChannelVariableMap map[VariableName]ChannelVariable

func (a ComparisonChannelVariableMap) MarshalJSON() ([]byte, error) {
	return safejson.Marshal(map[VariableName]ChannelVariable(a))
}

func (a *ComparisonChannelVariableMap) UnmarshalJSON(data []byte) error {
	var rawComparisonChannelVariableMap map[VariableName]ChannelVariable
	if err := safejson.Unmarshal(data, &rawComparisonChannelVariableMap); err != nil {
		return err
	}
	*a = ComparisonChannelVariableMap(rawComparisonChannelVariableMap)
	return nil
}

func (a ComparisonChannelVariableMap) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(a)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (a *ComparisonChannelVariableMap) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&a)
}

type ComparisonVizDefinitionMap map[api.VizId]VizDefinition

func (a ComparisonVizDefinitionMap) MarshalJSON() ([]byte, error) {
	return safejson.Marshal(map[api.VizId]VizDefinition(a))
}

func (a *ComparisonVizDefinitionMap) UnmarshalJSON(data []byte) error {
	var rawComparisonVizDefinitionMap map[api.VizId]VizDefinition
	if err := safejson.Unmarshal(data, &rawComparisonVizDefinitionMap); err != nil {
		return err
	}
	*a = ComparisonVizDefinitionMap(rawComparisonVizDefinitionMap)
	return nil
}

func (a ComparisonVizDefinitionMap) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(a)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (a *ComparisonVizDefinitionMap) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&a)
}

type VariableName string
