// Code generated by conjure-go. DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/nominal-io/nominal-api/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
	"github.com/palantir/pkg/uuid"
	werror "github.com/palantir/witchcraft-go-error"
)

type failedToCreateLogSet struct {
	Message string `json:"message"`
}

func (o failedToCreateLogSet) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *failedToCreateLogSet) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewFailedToCreateLogSet returns new instance of FailedToCreateLogSet error.
func NewFailedToCreateLogSet(messageArg string) *FailedToCreateLogSet {
	return &FailedToCreateLogSet{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), failedToCreateLogSet: failedToCreateLogSet{Message: messageArg}}
}

// WrapWithFailedToCreateLogSet returns new instance of FailedToCreateLogSet error wrapping an existing error.
func WrapWithFailedToCreateLogSet(err error, messageArg string) *FailedToCreateLogSet {
	return &FailedToCreateLogSet{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, failedToCreateLogSet: failedToCreateLogSet{Message: messageArg}}
}

// FailedToCreateLogSet is an error type.
type FailedToCreateLogSet struct {
	errorInstanceID uuid.UUID
	failedToCreateLogSet
	cause error
	stack werror.StackTrace
}

// IsFailedToCreateLogSet returns true if err is an instance of FailedToCreateLogSet.
func IsFailedToCreateLogSet(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*FailedToCreateLogSet)
	return ok
}

func (e *FailedToCreateLogSet) Error() string {
	return fmt.Sprintf("INTERNAL LogSet:FailedToCreateLogSet (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *FailedToCreateLogSet) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *FailedToCreateLogSet) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *FailedToCreateLogSet) Message() string {
	return "INTERNAL LogSet:FailedToCreateLogSet"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *FailedToCreateLogSet) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *FailedToCreateLogSet) Code() errors.ErrorCode {
	return errors.Internal
}

// Name returns an error name identifying error type.
func (e *FailedToCreateLogSet) Name() string {
	return "LogSet:FailedToCreateLogSet"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *FailedToCreateLogSet) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *FailedToCreateLogSet) Parameters() map[string]interface{} {
	return map[string]interface{}{"message": e.Message}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *FailedToCreateLogSet) safeParams() map[string]interface{} {
	return map[string]interface{}{"message": e.Message, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *FailedToCreateLogSet) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *FailedToCreateLogSet) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *FailedToCreateLogSet) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e FailedToCreateLogSet) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.failedToCreateLogSet)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.Internal, ErrorName: "LogSet:FailedToCreateLogSet", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *FailedToCreateLogSet) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters failedToCreateLogSet
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.failedToCreateLogSet = parameters
	return nil
}

type logSetAlreadyFinalized struct {
	Rid LogSetRid `json:"rid"`
}

func (o logSetAlreadyFinalized) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *logSetAlreadyFinalized) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewLogSetAlreadyFinalized returns new instance of LogSetAlreadyFinalized error.
func NewLogSetAlreadyFinalized(ridArg LogSetRid) *LogSetAlreadyFinalized {
	return &LogSetAlreadyFinalized{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), logSetAlreadyFinalized: logSetAlreadyFinalized{Rid: ridArg}}
}

// WrapWithLogSetAlreadyFinalized returns new instance of LogSetAlreadyFinalized error wrapping an existing error.
func WrapWithLogSetAlreadyFinalized(err error, ridArg LogSetRid) *LogSetAlreadyFinalized {
	return &LogSetAlreadyFinalized{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, logSetAlreadyFinalized: logSetAlreadyFinalized{Rid: ridArg}}
}

// LogSetAlreadyFinalized is an error type.
type LogSetAlreadyFinalized struct {
	errorInstanceID uuid.UUID
	logSetAlreadyFinalized
	cause error
	stack werror.StackTrace
}

// IsLogSetAlreadyFinalized returns true if err is an instance of LogSetAlreadyFinalized.
func IsLogSetAlreadyFinalized(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*LogSetAlreadyFinalized)
	return ok
}

func (e *LogSetAlreadyFinalized) Error() string {
	return fmt.Sprintf("INVALID_ARGUMENT LogSet:LogSetAlreadyFinalized (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *LogSetAlreadyFinalized) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *LogSetAlreadyFinalized) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *LogSetAlreadyFinalized) Message() string {
	return "INVALID_ARGUMENT LogSet:LogSetAlreadyFinalized"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *LogSetAlreadyFinalized) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *LogSetAlreadyFinalized) Code() errors.ErrorCode {
	return errors.InvalidArgument
}

// Name returns an error name identifying error type.
func (e *LogSetAlreadyFinalized) Name() string {
	return "LogSet:LogSetAlreadyFinalized"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *LogSetAlreadyFinalized) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *LogSetAlreadyFinalized) Parameters() map[string]interface{} {
	return map[string]interface{}{"rid": e.Rid}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *LogSetAlreadyFinalized) safeParams() map[string]interface{} {
	return map[string]interface{}{"rid": e.Rid, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *LogSetAlreadyFinalized) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *LogSetAlreadyFinalized) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *LogSetAlreadyFinalized) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e LogSetAlreadyFinalized) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.logSetAlreadyFinalized)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.InvalidArgument, ErrorName: "LogSet:LogSetAlreadyFinalized", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *LogSetAlreadyFinalized) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters logSetAlreadyFinalized
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.logSetAlreadyFinalized = parameters
	return nil
}

type logSetNotFound struct {
	Rid LogSetRid `json:"rid"`
}

func (o logSetNotFound) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *logSetNotFound) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewLogSetNotFound returns new instance of LogSetNotFound error.
func NewLogSetNotFound(ridArg LogSetRid) *LogSetNotFound {
	return &LogSetNotFound{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), logSetNotFound: logSetNotFound{Rid: ridArg}}
}

// WrapWithLogSetNotFound returns new instance of LogSetNotFound error wrapping an existing error.
func WrapWithLogSetNotFound(err error, ridArg LogSetRid) *LogSetNotFound {
	return &LogSetNotFound{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, logSetNotFound: logSetNotFound{Rid: ridArg}}
}

// LogSetNotFound is an error type.
type LogSetNotFound struct {
	errorInstanceID uuid.UUID
	logSetNotFound
	cause error
	stack werror.StackTrace
}

// IsLogSetNotFound returns true if err is an instance of LogSetNotFound.
func IsLogSetNotFound(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*LogSetNotFound)
	return ok
}

func (e *LogSetNotFound) Error() string {
	return fmt.Sprintf("NOT_FOUND LogSet:LogSetNotFound (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *LogSetNotFound) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *LogSetNotFound) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *LogSetNotFound) Message() string {
	return "NOT_FOUND LogSet:LogSetNotFound"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *LogSetNotFound) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *LogSetNotFound) Code() errors.ErrorCode {
	return errors.NotFound
}

// Name returns an error name identifying error type.
func (e *LogSetNotFound) Name() string {
	return "LogSet:LogSetNotFound"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *LogSetNotFound) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *LogSetNotFound) Parameters() map[string]interface{} {
	return map[string]interface{}{"rid": e.Rid}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *LogSetNotFound) safeParams() map[string]interface{} {
	return map[string]interface{}{"rid": e.Rid, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *LogSetNotFound) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *LogSetNotFound) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *LogSetNotFound) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e LogSetNotFound) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.logSetNotFound)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.NotFound, ErrorName: "LogSet:LogSetNotFound", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *LogSetNotFound) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters logSetNotFound
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.logSetNotFound = parameters
	return nil
}

func init() {
	conjureerrors.RegisterErrorType("LogSet:FailedToCreateLogSet", reflect.TypeOf(FailedToCreateLogSet{}))
	conjureerrors.RegisterErrorType("LogSet:LogSetAlreadyFinalized", reflect.TypeOf(LogSetAlreadyFinalized{}))
	conjureerrors.RegisterErrorType("LogSet:LogSetNotFound", reflect.TypeOf(LogSetNotFound{}))
}
