// Code generated by conjure-go. DO NOT EDIT.

package api

import (
	"strings"
)

type DataSourceType struct {
	val DataSourceType_Value
}

type DataSourceType_Value string

const (
	DataSourceType_DATASET    DataSourceType_Value = "DATASET"
	DataSourceType_CONNECTION DataSourceType_Value = "CONNECTION"
	DataSourceType_LOGSET     DataSourceType_Value = "LOGSET"
	DataSourceType_VIDEO      DataSourceType_Value = "VIDEO"
	DataSourceType_UNKNOWN    DataSourceType_Value = "UNKNOWN"
)

// DataSourceType_Values returns all known variants of DataSourceType.
func DataSourceType_Values() []DataSourceType_Value {
	return []DataSourceType_Value{DataSourceType_DATASET, DataSourceType_CONNECTION, DataSourceType_LOGSET, DataSourceType_VIDEO}
}

func New_DataSourceType(value DataSourceType_Value) DataSourceType {
	return DataSourceType{val: value}
}

// IsUnknown returns false for all known variants of DataSourceType and true otherwise.
func (e DataSourceType) IsUnknown() bool {
	switch e.val {
	case DataSourceType_DATASET, DataSourceType_CONNECTION, DataSourceType_LOGSET, DataSourceType_VIDEO:
		return false
	}
	return true
}

func (e DataSourceType) Value() DataSourceType_Value {
	if e.IsUnknown() {
		return DataSourceType_UNKNOWN
	}
	return e.val
}

func (e DataSourceType) String() string {
	return string(e.val)
}

func (e DataSourceType) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *DataSourceType) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_DataSourceType(DataSourceType_Value(v))
	case "DATASET":
		*e = New_DataSourceType(DataSourceType_DATASET)
	case "CONNECTION":
		*e = New_DataSourceType(DataSourceType_CONNECTION)
	case "LOGSET":
		*e = New_DataSourceType(DataSourceType_LOGSET)
	case "VIDEO":
		*e = New_DataSourceType(DataSourceType_VIDEO)
	}
	return nil
}

type RunDataReviewEvaluationStatus struct {
	val RunDataReviewEvaluationStatus_Value
}

type RunDataReviewEvaluationStatus_Value string

const (
	RunDataReviewEvaluationStatus_NO_CHECKS_APPLIED          RunDataReviewEvaluationStatus_Value = "NO_CHECKS_APPLIED"
	RunDataReviewEvaluationStatus_FAILED_TO_EXECUTE          RunDataReviewEvaluationStatus_Value = "FAILED_TO_EXECUTE"
	RunDataReviewEvaluationStatus_EXECUTING                  RunDataReviewEvaluationStatus_Value = "EXECUTING"
	RunDataReviewEvaluationStatus_PENDING_EXECUTION          RunDataReviewEvaluationStatus_Value = "PENDING_EXECUTION"
	RunDataReviewEvaluationStatus_CLOSED_WITH_FURTHER_ACTION RunDataReviewEvaluationStatus_Value = "CLOSED_WITH_FURTHER_ACTION"
	RunDataReviewEvaluationStatus_GENERATED_ALERTS           RunDataReviewEvaluationStatus_Value = "GENERATED_ALERTS"
	RunDataReviewEvaluationStatus_CLOSED_WITH_IGNORE         RunDataReviewEvaluationStatus_Value = "CLOSED_WITH_IGNORE"
	RunDataReviewEvaluationStatus_PASSING                    RunDataReviewEvaluationStatus_Value = "PASSING"
	RunDataReviewEvaluationStatus_UNKNOWN                    RunDataReviewEvaluationStatus_Value = "UNKNOWN"
)

// RunDataReviewEvaluationStatus_Values returns all known variants of RunDataReviewEvaluationStatus.
func RunDataReviewEvaluationStatus_Values() []RunDataReviewEvaluationStatus_Value {
	return []RunDataReviewEvaluationStatus_Value{RunDataReviewEvaluationStatus_NO_CHECKS_APPLIED, RunDataReviewEvaluationStatus_FAILED_TO_EXECUTE, RunDataReviewEvaluationStatus_EXECUTING, RunDataReviewEvaluationStatus_PENDING_EXECUTION, RunDataReviewEvaluationStatus_CLOSED_WITH_FURTHER_ACTION, RunDataReviewEvaluationStatus_GENERATED_ALERTS, RunDataReviewEvaluationStatus_CLOSED_WITH_IGNORE, RunDataReviewEvaluationStatus_PASSING}
}

func New_RunDataReviewEvaluationStatus(value RunDataReviewEvaluationStatus_Value) RunDataReviewEvaluationStatus {
	return RunDataReviewEvaluationStatus{val: value}
}

// IsUnknown returns false for all known variants of RunDataReviewEvaluationStatus and true otherwise.
func (e RunDataReviewEvaluationStatus) IsUnknown() bool {
	switch e.val {
	case RunDataReviewEvaluationStatus_NO_CHECKS_APPLIED, RunDataReviewEvaluationStatus_FAILED_TO_EXECUTE, RunDataReviewEvaluationStatus_EXECUTING, RunDataReviewEvaluationStatus_PENDING_EXECUTION, RunDataReviewEvaluationStatus_CLOSED_WITH_FURTHER_ACTION, RunDataReviewEvaluationStatus_GENERATED_ALERTS, RunDataReviewEvaluationStatus_CLOSED_WITH_IGNORE, RunDataReviewEvaluationStatus_PASSING:
		return false
	}
	return true
}

func (e RunDataReviewEvaluationStatus) Value() RunDataReviewEvaluationStatus_Value {
	if e.IsUnknown() {
		return RunDataReviewEvaluationStatus_UNKNOWN
	}
	return e.val
}

func (e RunDataReviewEvaluationStatus) String() string {
	return string(e.val)
}

func (e RunDataReviewEvaluationStatus) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *RunDataReviewEvaluationStatus) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_RunDataReviewEvaluationStatus(RunDataReviewEvaluationStatus_Value(v))
	case "NO_CHECKS_APPLIED":
		*e = New_RunDataReviewEvaluationStatus(RunDataReviewEvaluationStatus_NO_CHECKS_APPLIED)
	case "FAILED_TO_EXECUTE":
		*e = New_RunDataReviewEvaluationStatus(RunDataReviewEvaluationStatus_FAILED_TO_EXECUTE)
	case "EXECUTING":
		*e = New_RunDataReviewEvaluationStatus(RunDataReviewEvaluationStatus_EXECUTING)
	case "PENDING_EXECUTION":
		*e = New_RunDataReviewEvaluationStatus(RunDataReviewEvaluationStatus_PENDING_EXECUTION)
	case "CLOSED_WITH_FURTHER_ACTION":
		*e = New_RunDataReviewEvaluationStatus(RunDataReviewEvaluationStatus_CLOSED_WITH_FURTHER_ACTION)
	case "GENERATED_ALERTS":
		*e = New_RunDataReviewEvaluationStatus(RunDataReviewEvaluationStatus_GENERATED_ALERTS)
	case "CLOSED_WITH_IGNORE":
		*e = New_RunDataReviewEvaluationStatus(RunDataReviewEvaluationStatus_CLOSED_WITH_IGNORE)
	case "PASSING":
		*e = New_RunDataReviewEvaluationStatus(RunDataReviewEvaluationStatus_PASSING)
	}
	return nil
}

type SortField struct {
	val SortField_Value
}

type SortField_Value string

const (
	SortField_NAME                 SortField_Value = "NAME"
	SortField_CREATED_AT           SortField_Value = "CREATED_AT"
	SortField_START_TIME           SortField_Value = "START_TIME"
	SortField_END_TIME             SortField_Value = "END_TIME"
	SortField_PENDING_CHECK_ALERTS SortField_Value = "PENDING_CHECK_ALERTS"
	SortField_UNKNOWN              SortField_Value = "UNKNOWN"
)

// SortField_Values returns all known variants of SortField.
func SortField_Values() []SortField_Value {
	return []SortField_Value{SortField_NAME, SortField_CREATED_AT, SortField_START_TIME, SortField_END_TIME, SortField_PENDING_CHECK_ALERTS}
}

func New_SortField(value SortField_Value) SortField {
	return SortField{val: value}
}

// IsUnknown returns false for all known variants of SortField and true otherwise.
func (e SortField) IsUnknown() bool {
	switch e.val {
	case SortField_NAME, SortField_CREATED_AT, SortField_START_TIME, SortField_END_TIME, SortField_PENDING_CHECK_ALERTS:
		return false
	}
	return true
}

func (e SortField) Value() SortField_Value {
	if e.IsUnknown() {
		return SortField_UNKNOWN
	}
	return e.val
}

func (e SortField) String() string {
	return string(e.val)
}

func (e SortField) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *SortField) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_SortField(SortField_Value(v))
	case "NAME":
		*e = New_SortField(SortField_NAME)
	case "CREATED_AT":
		*e = New_SortField(SortField_CREATED_AT)
	case "START_TIME":
		*e = New_SortField(SortField_START_TIME)
	case "END_TIME":
		*e = New_SortField(SortField_END_TIME)
	case "PENDING_CHECK_ALERTS":
		*e = New_SortField(SortField_PENDING_CHECK_ALERTS)
	}
	return nil
}

// If a CSV data source is still being split, the timestamp type is not known.
type WeakTimestampType struct {
	val WeakTimestampType_Value
}

type WeakTimestampType_Value string

const (
	WeakTimestampType_ABSOLUTE WeakTimestampType_Value = "ABSOLUTE"
	WeakTimestampType_RELATIVE WeakTimestampType_Value = "RELATIVE"
	WeakTimestampType_PENDING  WeakTimestampType_Value = "PENDING"
	WeakTimestampType_UNKNOWN  WeakTimestampType_Value = "UNKNOWN"
)

// WeakTimestampType_Values returns all known variants of WeakTimestampType.
func WeakTimestampType_Values() []WeakTimestampType_Value {
	return []WeakTimestampType_Value{WeakTimestampType_ABSOLUTE, WeakTimestampType_RELATIVE, WeakTimestampType_PENDING}
}

func New_WeakTimestampType(value WeakTimestampType_Value) WeakTimestampType {
	return WeakTimestampType{val: value}
}

// IsUnknown returns false for all known variants of WeakTimestampType and true otherwise.
func (e WeakTimestampType) IsUnknown() bool {
	switch e.val {
	case WeakTimestampType_ABSOLUTE, WeakTimestampType_RELATIVE, WeakTimestampType_PENDING:
		return false
	}
	return true
}

func (e WeakTimestampType) Value() WeakTimestampType_Value {
	if e.IsUnknown() {
		return WeakTimestampType_UNKNOWN
	}
	return e.val
}

func (e WeakTimestampType) String() string {
	return string(e.val)
}

func (e WeakTimestampType) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *WeakTimestampType) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_WeakTimestampType(WeakTimestampType_Value(v))
	case "ABSOLUTE":
		*e = New_WeakTimestampType(WeakTimestampType_ABSOLUTE)
	case "RELATIVE":
		*e = New_WeakTimestampType(WeakTimestampType_RELATIVE)
	case "PENDING":
		*e = New_WeakTimestampType(WeakTimestampType_PENDING)
	}
	return nil
}
