// Code generated by conjure-go. DO NOT EDIT.

package api

import (
	"strings"
)

type NotebookType struct {
	val NotebookType_Value
}

type NotebookType_Value string

const (
	NotebookType_WORKBOOK            NotebookType_Value = "WORKBOOK"
	NotebookType_COMPARISON_WORKBOOK NotebookType_Value = "COMPARISON_WORKBOOK"
	NotebookType_UNKNOWN             NotebookType_Value = "UNKNOWN"
)

// NotebookType_Values returns all known variants of NotebookType.
func NotebookType_Values() []NotebookType_Value {
	return []NotebookType_Value{NotebookType_WORKBOOK, NotebookType_COMPARISON_WORKBOOK}
}

func New_NotebookType(value NotebookType_Value) NotebookType {
	return NotebookType{val: value}
}

// IsUnknown returns false for all known variants of NotebookType and true otherwise.
func (e NotebookType) IsUnknown() bool {
	switch e.val {
	case NotebookType_WORKBOOK, NotebookType_COMPARISON_WORKBOOK:
		return false
	}
	return true
}

func (e NotebookType) Value() NotebookType_Value {
	if e.IsUnknown() {
		return NotebookType_UNKNOWN
	}
	return e.val
}

func (e NotebookType) String() string {
	return string(e.val)
}

func (e NotebookType) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *NotebookType) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_NotebookType(NotebookType_Value(v))
	case "WORKBOOK":
		*e = New_NotebookType(NotebookType_WORKBOOK)
	case "COMPARISON_WORKBOOK":
		*e = New_NotebookType(NotebookType_COMPARISON_WORKBOOK)
	}
	return nil
}

type SortByField struct {
	val SortByField_Value
}

type SortByField_Value string

const (
	SortByField_NAME       SortByField_Value = "NAME"
	SortByField_CREATED_AT SortByField_Value = "CREATED_AT"
	SortByField_UPDATED_AT SortByField_Value = "UPDATED_AT"
	SortByField_UNKNOWN    SortByField_Value = "UNKNOWN"
)

// SortByField_Values returns all known variants of SortByField.
func SortByField_Values() []SortByField_Value {
	return []SortByField_Value{SortByField_NAME, SortByField_CREATED_AT, SortByField_UPDATED_AT}
}

func New_SortByField(value SortByField_Value) SortByField {
	return SortByField{val: value}
}

// IsUnknown returns false for all known variants of SortByField and true otherwise.
func (e SortByField) IsUnknown() bool {
	switch e.val {
	case SortByField_NAME, SortByField_CREATED_AT, SortByField_UPDATED_AT:
		return false
	}
	return true
}

func (e SortByField) Value() SortByField_Value {
	if e.IsUnknown() {
		return SortByField_UNKNOWN
	}
	return e.val
}

func (e SortByField) String() string {
	return string(e.val)
}

func (e SortByField) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *SortByField) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_SortByField(SortByField_Value(v))
	case "NAME":
		*e = New_SortByField(SortByField_NAME)
	case "CREATED_AT":
		*e = New_SortByField(SortByField_CREATED_AT)
	case "UPDATED_AT":
		*e = New_SortByField(SortByField_UPDATED_AT)
	}
	return nil
}
