// Code generated by conjure-go. DO NOT EDIT.

package api

import (
	"context"
	"fmt"

	"github.com/nominal-io/nominal-api-go/api/rids"
	"github.com/nominal-io/nominal-api-go/io/nominal/api"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

type SearchSecretsQuery struct {
	typ        string
	searchText *string
	label      *api.Label
	property   *api.Property
	and        *[]SearchSecretsQuery
	or         *[]SearchSecretsQuery
	workspace  *rids.WorkspaceRid
}

type searchSecretsQueryDeserializer struct {
	Type       string                `json:"type"`
	SearchText *string               `json:"searchText"`
	Label      *api.Label            `json:"label"`
	Property   *api.Property         `json:"property"`
	And        *[]SearchSecretsQuery `json:"and"`
	Or         *[]SearchSecretsQuery `json:"or"`
	Workspace  *rids.WorkspaceRid    `json:"workspace"`
}

func (u *searchSecretsQueryDeserializer) toStruct() SearchSecretsQuery {
	return SearchSecretsQuery{typ: u.Type, searchText: u.SearchText, label: u.Label, property: u.Property, and: u.And, or: u.Or, workspace: u.Workspace}
}

func (u *SearchSecretsQuery) toSerializer() (interface{}, error) {
	switch u.typ {
	default:
		return nil, fmt.Errorf("unknown type %q", u.typ)
	case "searchText":
		if u.searchText == nil {
			return nil, fmt.Errorf("field \"searchText\" is required")
		}
		return struct {
			Type       string `json:"type"`
			SearchText string `json:"searchText"`
		}{Type: "searchText", SearchText: *u.searchText}, nil
	case "label":
		if u.label == nil {
			return nil, fmt.Errorf("field \"label\" is required")
		}
		return struct {
			Type  string    `json:"type"`
			Label api.Label `json:"label"`
		}{Type: "label", Label: *u.label}, nil
	case "property":
		if u.property == nil {
			return nil, fmt.Errorf("field \"property\" is required")
		}
		return struct {
			Type     string       `json:"type"`
			Property api.Property `json:"property"`
		}{Type: "property", Property: *u.property}, nil
	case "and":
		if u.and == nil {
			return nil, fmt.Errorf("field \"and\" is required")
		}
		return struct {
			Type string               `json:"type"`
			And  []SearchSecretsQuery `json:"and"`
		}{Type: "and", And: *u.and}, nil
	case "or":
		if u.or == nil {
			return nil, fmt.Errorf("field \"or\" is required")
		}
		return struct {
			Type string               `json:"type"`
			Or   []SearchSecretsQuery `json:"or"`
		}{Type: "or", Or: *u.or}, nil
	case "workspace":
		if u.workspace == nil {
			return nil, fmt.Errorf("field \"workspace\" is required")
		}
		return struct {
			Type      string            `json:"type"`
			Workspace rids.WorkspaceRid `json:"workspace"`
		}{Type: "workspace", Workspace: *u.workspace}, nil
	}
}

func (u SearchSecretsQuery) MarshalJSON() ([]byte, error) {
	ser, err := u.toSerializer()
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(ser)
}

func (u *SearchSecretsQuery) UnmarshalJSON(data []byte) error {
	var deser searchSecretsQueryDeserializer
	if err := safejson.Unmarshal(data, &deser); err != nil {
		return err
	}
	*u = deser.toStruct()
	switch u.typ {
	case "searchText":
		if u.searchText == nil {
			return fmt.Errorf("field \"searchText\" is required")
		}
	case "label":
		if u.label == nil {
			return fmt.Errorf("field \"label\" is required")
		}
	case "property":
		if u.property == nil {
			return fmt.Errorf("field \"property\" is required")
		}
	case "and":
		if u.and == nil {
			return fmt.Errorf("field \"and\" is required")
		}
	case "or":
		if u.or == nil {
			return fmt.Errorf("field \"or\" is required")
		}
	case "workspace":
		if u.workspace == nil {
			return fmt.Errorf("field \"workspace\" is required")
		}
	}
	return nil
}

func (u SearchSecretsQuery) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(u)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (u *SearchSecretsQuery) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&u)
}

func (u *SearchSecretsQuery) AcceptFuncs(searchTextFunc func(string) error, labelFunc func(api.Label) error, propertyFunc func(api.Property) error, andFunc func([]SearchSecretsQuery) error, orFunc func([]SearchSecretsQuery) error, workspaceFunc func(rids.WorkspaceRid) error, unknownFunc func(string) error) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return unknownFunc(u.typ)
	case "searchText":
		if u.searchText == nil {
			return fmt.Errorf("field \"searchText\" is required")
		}
		return searchTextFunc(*u.searchText)
	case "label":
		if u.label == nil {
			return fmt.Errorf("field \"label\" is required")
		}
		return labelFunc(*u.label)
	case "property":
		if u.property == nil {
			return fmt.Errorf("field \"property\" is required")
		}
		return propertyFunc(*u.property)
	case "and":
		if u.and == nil {
			return fmt.Errorf("field \"and\" is required")
		}
		return andFunc(*u.and)
	case "or":
		if u.or == nil {
			return fmt.Errorf("field \"or\" is required")
		}
		return orFunc(*u.or)
	case "workspace":
		if u.workspace == nil {
			return fmt.Errorf("field \"workspace\" is required")
		}
		return workspaceFunc(*u.workspace)
	}
}

func (u *SearchSecretsQuery) SearchTextNoopSuccess(string) error {
	return nil
}

func (u *SearchSecretsQuery) LabelNoopSuccess(api.Label) error {
	return nil
}

func (u *SearchSecretsQuery) PropertyNoopSuccess(api.Property) error {
	return nil
}

func (u *SearchSecretsQuery) AndNoopSuccess([]SearchSecretsQuery) error {
	return nil
}

func (u *SearchSecretsQuery) OrNoopSuccess([]SearchSecretsQuery) error {
	return nil
}

func (u *SearchSecretsQuery) WorkspaceNoopSuccess(rids.WorkspaceRid) error {
	return nil
}

func (u *SearchSecretsQuery) ErrorOnUnknown(typeName string) error {
	return fmt.Errorf("invalid value in union type. Type name: %s", typeName)
}

func (u *SearchSecretsQuery) Accept(v SearchSecretsQueryVisitor) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknown(u.typ)
	case "searchText":
		if u.searchText == nil {
			return fmt.Errorf("field \"searchText\" is required")
		}
		return v.VisitSearchText(*u.searchText)
	case "label":
		if u.label == nil {
			return fmt.Errorf("field \"label\" is required")
		}
		return v.VisitLabel(*u.label)
	case "property":
		if u.property == nil {
			return fmt.Errorf("field \"property\" is required")
		}
		return v.VisitProperty(*u.property)
	case "and":
		if u.and == nil {
			return fmt.Errorf("field \"and\" is required")
		}
		return v.VisitAnd(*u.and)
	case "or":
		if u.or == nil {
			return fmt.Errorf("field \"or\" is required")
		}
		return v.VisitOr(*u.or)
	case "workspace":
		if u.workspace == nil {
			return fmt.Errorf("field \"workspace\" is required")
		}
		return v.VisitWorkspace(*u.workspace)
	}
}

type SearchSecretsQueryVisitor interface {
	VisitSearchText(v string) error
	VisitLabel(v api.Label) error
	VisitProperty(v api.Property) error
	VisitAnd(v []SearchSecretsQuery) error
	VisitOr(v []SearchSecretsQuery) error
	VisitWorkspace(v rids.WorkspaceRid) error
	VisitUnknown(typeName string) error
}

func (u *SearchSecretsQuery) AcceptWithContext(ctx context.Context, v SearchSecretsQueryVisitorWithContext) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknownWithContext(ctx, u.typ)
	case "searchText":
		if u.searchText == nil {
			return fmt.Errorf("field \"searchText\" is required")
		}
		return v.VisitSearchTextWithContext(ctx, *u.searchText)
	case "label":
		if u.label == nil {
			return fmt.Errorf("field \"label\" is required")
		}
		return v.VisitLabelWithContext(ctx, *u.label)
	case "property":
		if u.property == nil {
			return fmt.Errorf("field \"property\" is required")
		}
		return v.VisitPropertyWithContext(ctx, *u.property)
	case "and":
		if u.and == nil {
			return fmt.Errorf("field \"and\" is required")
		}
		return v.VisitAndWithContext(ctx, *u.and)
	case "or":
		if u.or == nil {
			return fmt.Errorf("field \"or\" is required")
		}
		return v.VisitOrWithContext(ctx, *u.or)
	case "workspace":
		if u.workspace == nil {
			return fmt.Errorf("field \"workspace\" is required")
		}
		return v.VisitWorkspaceWithContext(ctx, *u.workspace)
	}
}

type SearchSecretsQueryVisitorWithContext interface {
	VisitSearchTextWithContext(ctx context.Context, v string) error
	VisitLabelWithContext(ctx context.Context, v api.Label) error
	VisitPropertyWithContext(ctx context.Context, v api.Property) error
	VisitAndWithContext(ctx context.Context, v []SearchSecretsQuery) error
	VisitOrWithContext(ctx context.Context, v []SearchSecretsQuery) error
	VisitWorkspaceWithContext(ctx context.Context, v rids.WorkspaceRid) error
	VisitUnknownWithContext(ctx context.Context, typeName string) error
}

func NewSearchSecretsQueryFromSearchText(v string) SearchSecretsQuery {
	return SearchSecretsQuery{typ: "searchText", searchText: &v}
}

func NewSearchSecretsQueryFromLabel(v api.Label) SearchSecretsQuery {
	return SearchSecretsQuery{typ: "label", label: &v}
}

func NewSearchSecretsQueryFromProperty(v api.Property) SearchSecretsQuery {
	return SearchSecretsQuery{typ: "property", property: &v}
}

func NewSearchSecretsQueryFromAnd(v []SearchSecretsQuery) SearchSecretsQuery {
	return SearchSecretsQuery{typ: "and", and: &v}
}

func NewSearchSecretsQueryFromOr(v []SearchSecretsQuery) SearchSecretsQuery {
	return SearchSecretsQuery{typ: "or", or: &v}
}

func NewSearchSecretsQueryFromWorkspace(v rids.WorkspaceRid) SearchSecretsQuery {
	return SearchSecretsQuery{typ: "workspace", workspace: &v}
}
