exclude:
  names:
    - "\\..+"
    - "vendor"
  paths:
    - "godel"
plugins:
  resolvers:
    - "https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz"
  plugins:
    - locator:
        id: "com.palantir.godel-conjure-plugin:conjure-plugin:6.104.0"
        checksums:
          darwin-arm64: "25e8a27037b0827226b3740847b31ea6f4f62eda5e388003c0d51667df048b47"
