// Code generated by conjure-go. DO NOT EDIT.

package api

import (
	"context"
	"fmt"

	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

type Handle struct {
	typ string
	s3  *S3Handle
}

type handleDeserializer struct {
	Type string    `json:"type"`
	S3   *S3Handle `json:"s3"`
}

func (u *handleDeserializer) toStruct() Handle {
	return Handle{typ: u.Type, s3: u.S3}
}

func (u *Handle) toSerializer() (interface{}, error) {
	switch u.typ {
	default:
		return nil, fmt.Errorf("unknown type %q", u.typ)
	case "s3":
		if u.s3 == nil {
			return nil, fmt.Errorf("field \"s3\" is required")
		}
		return struct {
			Type string   `json:"type"`
			S3   S3Handle `json:"s3"`
		}{Type: "s3", S3: *u.s3}, nil
	}
}

func (u Handle) MarshalJSON() ([]byte, error) {
	ser, err := u.toSerializer()
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(ser)
}

func (u *Handle) UnmarshalJSON(data []byte) error {
	var deser handleDeserializer
	if err := safejson.Unmarshal(data, &deser); err != nil {
		return err
	}
	*u = deser.toStruct()
	switch u.typ {
	case "s3":
		if u.s3 == nil {
			return fmt.Errorf("field \"s3\" is required")
		}
	}
	return nil
}

func (u Handle) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(u)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (u *Handle) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&u)
}

func (u *Handle) AcceptFuncs(s3Func func(S3Handle) error, unknownFunc func(string) error) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return unknownFunc(u.typ)
	case "s3":
		if u.s3 == nil {
			return fmt.Errorf("field \"s3\" is required")
		}
		return s3Func(*u.s3)
	}
}

func (u *Handle) S3NoopSuccess(S3Handle) error {
	return nil
}

func (u *Handle) ErrorOnUnknown(typeName string) error {
	return fmt.Errorf("invalid value in union type. Type name: %s", typeName)
}

func (u *Handle) Accept(v HandleVisitor) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknown(u.typ)
	case "s3":
		if u.s3 == nil {
			return fmt.Errorf("field \"s3\" is required")
		}
		return v.VisitS3(*u.s3)
	}
}

type HandleVisitor interface {
	VisitS3(v S3Handle) error
	VisitUnknown(typeName string) error
}

func (u *Handle) AcceptWithContext(ctx context.Context, v HandleVisitorWithContext) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknownWithContext(ctx, u.typ)
	case "s3":
		if u.s3 == nil {
			return fmt.Errorf("field \"s3\" is required")
		}
		return v.VisitS3WithContext(ctx, *u.s3)
	}
}

type HandleVisitorWithContext interface {
	VisitS3WithContext(ctx context.Context, v S3Handle) error
	VisitUnknownWithContext(ctx context.Context, typeName string) error
}

func NewHandleFromS3(v S3Handle) Handle {
	return Handle{typ: "s3", s3: &v}
}
