// Code generated by conjure-go. DO NOT EDIT.

package download

import (
	"strings"
)

type Platform struct {
	val Platform_Value
}

type Platform_Value string

const (
	Platform_WINDOWS Platform_Value = "WINDOWS"
	Platform_UBUNTU  Platform_Value = "UBUNTU"
	Platform_MACOS   Platform_Value = "MACOS"
	Platform_UNKNOWN Platform_Value = "UNKNOWN"
)

// Platform_Values returns all known variants of Platform.
func Platform_Values() []Platform_Value {
	return []Platform_Value{Platform_WINDOWS, Platform_UBUNTU, Platform_MACOS}
}

func New_Platform(value Platform_Value) Platform {
	return Platform{val: value}
}

// IsUnknown returns false for all known variants of Platform and true otherwise.
func (e Platform) IsUnknown() bool {
	switch e.val {
	case Platform_WINDOWS, Platform_UBUNTU, Platform_MACOS:
		return false
	}
	return true
}

func (e Platform) Value() Platform_Value {
	if e.IsUnknown() {
		return Platform_UNKNOWN
	}
	return e.val
}

func (e Platform) String() string {
	return string(e.val)
}

func (e Platform) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *Platform) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_Platform(Platform_Value(v))
	case "WINDOWS":
		*e = New_Platform(Platform_WINDOWS)
	case "UBUNTU":
		*e = New_Platform(Platform_UBUNTU)
	case "MACOS":
		*e = New_Platform(Platform_MACOS)
	}
	return nil
}
