// Code generated by conjure-go. DO NOT EDIT.

package api

import (
	"context"
	"fmt"

	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

// The parent of a comment. It can be a resource or another comment in the case of a reply.
type CommentParent struct {
	typ      string
	resource *CommentParentResource
	comment  *CommentParentComment
}

type commentParentDeserializer struct {
	Type     string                 `json:"type"`
	Resource *CommentParentResource `json:"resource"`
	Comment  *CommentParentComment  `json:"comment"`
}

func (u *commentParentDeserializer) toStruct() CommentParent {
	return CommentParent{typ: u.Type, resource: u.Resource, comment: u.Comment}
}

func (u *CommentParent) toSerializer() (interface{}, error) {
	switch u.typ {
	default:
		return nil, fmt.Errorf("unknown type %q", u.typ)
	case "resource":
		if u.resource == nil {
			return nil, fmt.Errorf("field \"resource\" is required")
		}
		return struct {
			Type     string                `json:"type"`
			Resource CommentParentResource `json:"resource"`
		}{Type: "resource", Resource: *u.resource}, nil
	case "comment":
		if u.comment == nil {
			return nil, fmt.Errorf("field \"comment\" is required")
		}
		return struct {
			Type    string               `json:"type"`
			Comment CommentParentComment `json:"comment"`
		}{Type: "comment", Comment: *u.comment}, nil
	}
}

func (u CommentParent) MarshalJSON() ([]byte, error) {
	ser, err := u.toSerializer()
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(ser)
}

func (u *CommentParent) UnmarshalJSON(data []byte) error {
	var deser commentParentDeserializer
	if err := safejson.Unmarshal(data, &deser); err != nil {
		return err
	}
	*u = deser.toStruct()
	switch u.typ {
	case "resource":
		if u.resource == nil {
			return fmt.Errorf("field \"resource\" is required")
		}
	case "comment":
		if u.comment == nil {
			return fmt.Errorf("field \"comment\" is required")
		}
	}
	return nil
}

func (u CommentParent) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(u)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (u *CommentParent) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&u)
}

func (u *CommentParent) AcceptFuncs(resourceFunc func(CommentParentResource) error, commentFunc func(CommentParentComment) error, unknownFunc func(string) error) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return unknownFunc(u.typ)
	case "resource":
		if u.resource == nil {
			return fmt.Errorf("field \"resource\" is required")
		}
		return resourceFunc(*u.resource)
	case "comment":
		if u.comment == nil {
			return fmt.Errorf("field \"comment\" is required")
		}
		return commentFunc(*u.comment)
	}
}

func (u *CommentParent) ResourceNoopSuccess(CommentParentResource) error {
	return nil
}

func (u *CommentParent) CommentNoopSuccess(CommentParentComment) error {
	return nil
}

func (u *CommentParent) ErrorOnUnknown(typeName string) error {
	return fmt.Errorf("invalid value in union type. Type name: %s", typeName)
}

func (u *CommentParent) Accept(v CommentParentVisitor) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknown(u.typ)
	case "resource":
		if u.resource == nil {
			return fmt.Errorf("field \"resource\" is required")
		}
		return v.VisitResource(*u.resource)
	case "comment":
		if u.comment == nil {
			return fmt.Errorf("field \"comment\" is required")
		}
		return v.VisitComment(*u.comment)
	}
}

type CommentParentVisitor interface {
	VisitResource(v CommentParentResource) error
	VisitComment(v CommentParentComment) error
	VisitUnknown(typeName string) error
}

func (u *CommentParent) AcceptWithContext(ctx context.Context, v CommentParentVisitorWithContext) error {
	switch u.typ {
	default:
		if u.typ == "" {
			return fmt.Errorf("invalid value in union type")
		}
		return v.VisitUnknownWithContext(ctx, u.typ)
	case "resource":
		if u.resource == nil {
			return fmt.Errorf("field \"resource\" is required")
		}
		return v.VisitResourceWithContext(ctx, *u.resource)
	case "comment":
		if u.comment == nil {
			return fmt.Errorf("field \"comment\" is required")
		}
		return v.VisitCommentWithContext(ctx, *u.comment)
	}
}

type CommentParentVisitorWithContext interface {
	VisitResourceWithContext(ctx context.Context, v CommentParentResource) error
	VisitCommentWithContext(ctx context.Context, v CommentParentComment) error
	VisitUnknownWithContext(ctx context.Context, typeName string) error
}

func NewCommentParentFromResource(v CommentParentResource) CommentParent {
	return CommentParent{typ: "resource", resource: &v}
}

func NewCommentParentFromComment(v CommentParentComment) CommentParent {
	return CommentParent{typ: "comment", comment: &v}
}
